# Generated by Django 4.2.7 on 2025-11-06 19:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('family', models.CharField(max_length=100)),
                ('is_featured', models.BooleanField(default=False)),
                ('hero_image', models.CharField(help_text='Path to hero image (e.g., assets/images/one.webp)', max_length=200)),
                ('engine_cc', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('cc_category', models.CharField(max_length=50)),
                ('power', models.CharField(max_length=100)),
                ('torque', models.CharField(max_length=100)),
                ('cooling', models.CharField(max_length=100)),
                ('transmission', models.CharField(max_length=100)),
                ('mileage', models.CharField(max_length=100)),
                ('top_speed', models.CharField(max_length=100)),
                ('performance_summary', models.TextField()),
                ('front_brake', models.CharField(max_length=200)),
                ('rear_brake', models.CharField(max_length=200)),
                ('suspension', models.CharField(max_length=200)),
                ('weight', models.CharField(max_length=50)),
                ('seat_height', models.CharField(max_length=50)),
                ('colors', models.TextField(help_text='Enter colors separated by commas')),
                ('ex_showroom_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('on_road_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('emi', models.CharField(help_text='e.g., ₹3,599/month', max_length=100)),
                ('features', models.TextField(help_text='Enter features separated by commas or newlines')),
                ('gallery_images', models.TextField(blank=True, help_text='Enter image paths separated by commas')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bike',
                'verbose_name_plural': 'Bikes',
                'ordering': ['-is_featured', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Discount percentage (e.g., 10.00 for 10%)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Discount amount in rupees', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.CharField(blank=True, help_text='Path to offer image (optional)', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bike', models.ForeignKey(blank=True, help_text='Leave blank for general offers', null=True, on_delete=django.db.models.deletion.CASCADE, to='showroom.bike')),
            ],
            options={
                'verbose_name': 'Offer',
                'verbose_name_plural': 'Offers',
                'ordering': ['-is_active', '-valid_from'],
            },
        ),
    ]
