# Generated by Django 4.2.7 on 2025-11-06 19:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0002_bike_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='cc_category',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='bike',
            name='colors',
            field=models.TextField(blank=True, default='', help_text='Enter colors separated by commas'),
        ),
        migrations.AlterField(
            model_name='bike',
            name='cooling',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='bike',
            name='emi',
            field=models.CharField(blank=True, default='', help_text='e.g., ₹3,599/month', max_length=100),
        ),
        migrations.AlterField(
            model_name='bike',
            name='engine_cc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='bike',
            name='ex_showroom_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='bike',
            name='family',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='bike',
            name='features',
            field=models.TextField(blank=True, default='', help_text='Enter features separated by commas or newlines'),
        ),
        migrations.AlterField(
            model_name='bike',
            name='front_brake',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='bike',
            name='gallery_images',
            field=models.TextField(blank=True, default='', help_text='Enter image paths separated by commas'),
        ),
        migrations.AlterField(
            model_name='bike',
            name='hero_image',
            field=models.CharField(blank=True, help_text='Path to hero image (e.g., assets/images/one.webp)', max_length=200),
        ),
        migrations.AlterField(
            model_name='bike',
            name='mileage',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='bike',
            name='on_road_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='bike',
            name='performance_summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='bike',
            name='power',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='bike',
            name='rear_brake',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='bike',
            name='seat_height',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='bike',
            name='suspension',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='bike',
            name='top_speed',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='bike',
            name='torque',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='bike',
            name='transmission',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='bike',
            name='weight',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
